routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*______________________________________________________________________________________________________________________
|
|                                              USER SIDE
| ______________________________________________________________________________________________________________________
*/
Route::namespace('UserSide')->group(function () {
    Route::get('/', function () {
        return redirect()->route('home');
    });
    Route::get('/dishes', 'DishController@showDishes')->name('dishes');
    Route::get('/dish/{dish}', 'DishController@showDish')->name('dish');
    Route::get('/search/dishes/autocomplete', 'SearchController@findDishesAutocomplete')->name('search.dishes.auto');
});
/*______________________________________________________________________________________________________________________
|
|                                              USER SIDE V2
| ______________________________________________________________________________________________________________________
*/
Route::namespace('UserSideV2')->group(function () {
    Route::prefix('v2')->group(function () {
        Route::get('/', 'MenuController@index')->name('home');
        Route::get('/cart', 'CartController@showCart')->name('cart');
        Route::post('/cart/recalculate', 'CartController@recalculateTotalPrice')->name('cart.recalculate');
        Route::any('/order/inc_item', 'OrderController@increaseOrderCounter')->name('orders.inc');
        Route::any('/order/dec_item', 'OrderController@decreaseOrderCount')->name('orders.dec');
        Route::any('/order/remove_item', 'OrderController@removeOrderItem')->name('orders.remove');
        Route::any('/order/confirm_order', 'OrderController@confirmOrder')->name('orders.confirm');
    });
});
/*______________________________________________________________________________________________________________________
|
|                                              ADMIN SIDE
| ______________________________________________________________________________________________________________________
*/
Route::prefix('admin')->group(function () {
    Route::namespace('AdminSide')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/dashboard/get_chart_data', 'DashboardController@getChartData')->name('dashboard.getChartData');
        /*______________________________________________________________________________________________________________
        |
        |                                              AUTH
        | ______________________________________________________________________________________________________________
        */
        Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login.form');
        Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/password/reset', 'Auth\ForgotPasswordController@reset');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
        /*______________________________________________________________________________________________________________
        |
        |                                              DISH
        | ______________________________________________________________________________________________________________
        */
        Route::middleware(['auth'])->group(function () {
            Route::get('/dishes/export', 'ExportController@showForm')->name('dishes.export.form');
            Route::match(['post', 'get'], '/dishes/history', 'ExportController@showHistory')->name('dishes.history');
            Route::post('/dishes/export', 'ExportController@export')->name('dishes.export');
        });
        /*______________________________________________________________________________________________________________
        |
        |                                              RESOURCES
        | ______________________________________________________________________________________________________________
        */
        Route::middleware(['auth'])->group(function () {
            Route::namespace('Resources')->group(function () {
                Route::resources([
                    'ingredients' => 'IngredientController',
                    'categories' => 'CategoryController',
                    'dishes' => 'DishController',
                    'menus' => 'MenuController',
                    'discounts' => 'DiscountController',
                    'delivery_types' => 'DeliveryTypeController',
                ]);
            });
        });
        /*______________________________________________________________________________________________________________
        |
        |                                              USER
        | ______________________________________________________________________________________________________________
        */
        Route::get('/users/create/{token}', 'UserRegisterController@showPostCreateForm')
            ->middleware('token.exists:user_registers')
            ->name('post.create.form');
        Route::post('/users/create/{token}', 'UserRegisterController@postCreateUser')->name('post.create.user');
        Route::middleware(['auth'])->group(function () {
            Route::middleware(['min.access.level:2'])->group(function () {
                Route::get('/users/create', 'UserRegisterController@showPreCreateForm')
                    ->name('pre.create.form');
                Route::post('/users/create', 'UserRegisterController@preCreateUser')
                    ->name('pre.create.user');
                Route::namespace('Resources')->group(function () {
                    Route::get('/users', 'UserController@index')
                        ->name('users.index');
                    Route::middleware(['compare.access.level'])->group(function () {
                        Route::get('/users/{user}/edit', 'UserController@edit')
                            ->name('users.edit');
                        Route::put('/users/{user} ', 'UserController@update')
                            ->name('users.update');
                        Route::delete('/users/{user}', 'UserController@destroy')
                            ->name('users.destroy');
                    });
                });
            });
        });
    });
});

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Ingredient
 * @package App\Models
 */
class Ingredient extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function dishes()
    {
        return $this->belongsToMany(
            Dish::class,
            'dish_ingredients',
            'ingredient_id',
            'dish_id'
        );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function photo()
    {
        return $this->morphOne(Photo::class, 'photoable');
    }
}

app/Http/Controllers/AdminSide/Resources/IngredientController.php
<?php

namespace App\Http\Controllers\AdminSide\Resources;

use App\Http\Requests\CreateIngredientRequest;
use App\Http\Requests\UpdateIngredientRequest;
use App\Models\Ingredient;
use App\Services\IntermediateManagers\IngredientIntermediateManager;
use App\Services\Managers\IngredientManager;
use App\Services\Repositories\IngredientRepository;
use App\Http\Controllers\Controller;

/**
 * Class IngredientController
 * @package App\Http\Controllers\AdminSide\Resources
 */
class IngredientController extends Controller
{
    /**
     * @var IngredientRepository
     */
    protected $ingredientRepository;

    /**
     * @var IngredientIntermediateManager
     */
    protected $ingredientIntermediateManager;

    /**
     * IngredientController constructor.
     * @param IngredientRepository $ingredientRepository
     * @param IngredientIntermediateManager $ingredientIntermediateManager
     */
    public function __construct(
        IngredientRepository $ingredientRepository,
        IngredientIntermediateManager $ingredientIntermediateManager
    ) {
        $this->ingredientRepository = $ingredientRepository;
        $this->ingredientIntermediateManager = $ingredientIntermediateManager;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $ingredients = $this->ingredientRepository->paginate(10);
        $ingredients->load('photo');

        return view('admin-side.entities.ingredient.index', compact('ingredients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin-side.entities.ingredient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateIngredientRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateIngredientRequest $request)
    {
        $this->ingredientIntermediateManager->create($request->except('_token'));

        return redirect()->route('ingredients.index')
            ->with('success', 'New ingredient has been successfully created.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Ingredient $ingredient
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Ingredient $ingredient)
    {
        return view('admin-side.entities.ingredient.edit', compact('ingredient'));
    }

    /**
     * @param UpdateIngredientRequest $request
     * @param Ingredient $ingredient
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function update(UpdateIngredientRequest $request, Ingredient $ingredient)
    {
        $this->ingredientIntermediateManager->update($ingredient, $request->except(['_token', '_method']));

        return redirect()->route('ingredients.index', $ingredient)
            ->with('success', 'Ingredient has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param IngredientManager $ingredientManager
     * @param Ingredient $ingredient
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(IngredientManager $ingredientManager, Ingredient $ingredient)
    {
        $ingredientManager->delete($ingredient);

        return redirect()->route('ingredients.index')
            ->with('success', 'Ingredient has been successfully deleted.');
    }
}

resources/views/admin-side/entities/ingredient/create.blade.php
@extends('layouts.main')

@section('title', 'Add ingredient')

@section('content')
    <div class="offset-md-1 col-md-10" style="padding-top: 10%;">
        <form id="update" class="single-form" action="{{ route('ingredients.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="form-group">
                <label for="name" class="control-label">Ingredient name</label>
                <input type="text" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="name" value="{{ old('name') }}">
                @if ($errors->has('name'))
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
            <div class="form-group">
                <label for="photo" class="control-label">Ingredient photo</label>
                <br>
                <input type="file" name="photo" id="photo">
            </div>
            <button class="btn btn-success">Add</button>
        </form>
    </div>
@endsection

@section('scripts')
    <script>
        $('#update').validate({
            errorClass: 'is-invalid',
            rules: {
                name: 'required'
            },
            messages: {
                name: 'Ingredient name field is required.'
            }
        });
    </script>
@endsection

resources/views/admin-side/entities/ingredient/edit.blade.php
@extends('layouts.main')

@section('title', 'Update ingredient')

@section('content')
    <div class="offset-md-1 col-md-10" style="padding-top: 10%;">
        <form id="update" action="{{ route('ingredients.update', $ingredient) }}" class="single-form" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="id" value="{{ $ingredient->id }}">
            <div class="form-group">
                <label for="name" class="control-label">Ingredient name</label>
                <input type="text" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="name" value="{{ $ingredient->name }}">
                @if ($errors->has('name'))
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
            <div class="form-group">
                <label for="photo" class="control-label">Ingredient photo</label>
                <br>
                <input type="file" name="photo" id="photo">
            </div>
            <button class="btn btn-success">Update</button>
        </form>
    </div>
@endsection

@section('scripts')
    <script>
        $('#update').validate({
            errorClass: 'is-invalid',
            rules: {
                name: 'required'
            },
            messages: {
                name: 'Ingredient name field is required.'
            }
        });
    </script>
@endsection

resources/views/admin-side/entities/ingredient/index.blade.php
@extends('layouts.main')

@section('title', 'Ingredients')

@section('modal')
    <div class="modal fade" id="delete_message" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure that you want to delete this ingredient?
                </div>
                <div class="modal-footer">
                    <button type="button" name="confirm" class="btn btn-success col-md-6">Confirm</button>
                    <button type="button" name="close" class="btn btn-secondary col-md-6" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="offset-md-1 col-md-10">
        <div class="col-md-12" style="margin-top: 25px">
            <a href="{{ route('ingredients.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> Add new ingredient</a>
        </div>
        <hr>
        <table class="table table-hover" style="margin-top: 25px; margin-bottom: 25px;">
            <thead>
            <tr class="text-uppercase text-center row">
                <th class="col-md-3 list-group-item-primary">Name</th>
                <th class="col-md-6 list-group-item-primary">Image</th>
                <th class="col-md-3 list-group-item-primary">Manage</th>
            </tr>
            </thead>
            <tbody>
            @forelse($ingredients as $ingredient)
                <tr class="text-center row">
                    <td class="col-md-3 d-flex align-items-center justify-content-center">
                        <p href="{{ route('ingredients.show', $ingredient) }}">{{ $ingredient->name }}</p>
                    </td>
                    <td class="col-md-6 d-flex align-items-center justify-content-center">
                        <img class="img img-fluid"
                             src="http://restaurant.admin.com/storage/ingredients/{{ $ingredient->photo ? $ingredient->photo->name : 'default.png' }}"
                             alt="{{ $ingredient->name }}"
                             width="200px"
                             height="150px">
                    </td>
                    <td class="col-md-3 d-flex align-items-center justify-content-center">
                        <form id="{{ $ingredient->name }}" action="{{ route('ingredients.destroy', $ingredient) }}" method="POST">
                            {{ csrf_field() }}
                            <a href="{{ route('ingredients.edit', $ingredient) }}" class="btn btn-success">
                                <i class="far fa-edit"></i>
                            </a>
                            <input type="hidden" name="_method" value="DELETE">
                            <button name="predeletion" type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_message">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center">No ingredients were found</td>
                </tr>
            @endforelse
            </tbody>
        </table>
        <hr>
        <diw class="d-flex justify-content-center">
            {{ $ingredients->links() }}
        </diw>
    </div>
@endsection

@section('scripts')
    <script src="{{ URL::asset('js/modal.js') }}"></script>
@endsection